### ISSUE TITLE
Use getBoundingClientRect instead of OffsetY in useInViewScroll

### ISSUE THREAD

**Issue by DanProudfoot** [matthiaaas/framer-motion-hooks#4]
Just found this while trying to do some Parallax with Framer Motion. Because `elPosY` uses `node.offsetTop` everything falls apart when used on an absolutely-positioned element.

I propose just replacing that line with:

```
 var elPosY = node.getBoundingClientRect().top + scrollY.get();
```

I would submit this as a pull request, but I don't know the implications for the other hooks, or if this is the best approach in all situations

**Comment by matthiaaas** [comment]
Hey @DanProudfoot, I wasn't aware of this bug, thanks. This is fine so feel free to open a PR. Otherwise I will roll out a fix in a few days.

From my experiences, `getBoundingClientRect()` sometimes introduces performance issues in some browsers, but we'll see. I don't think the performance will decrease noticeably.

But if so, maybe a MutationObserver would solve that problem.

**Comment by DanProudfoot** [comment]
Just looked into ResizeObserver and that comes back with the top and Y property as 0, just like offsetTop. I don't really understand the rationale for a having a measurement API that breaks down the second Absolute positioning is used, but I guess that's what we're lumbered with. 

If required, I could send my pull request with a toggle, so that it uses one of the two options depending on needs and perf?

**Comment by matthiaaas** [comment]
For now, I don't think we need to optimize this so no need for a toggle. That one-line-change PR is fine ^^

Thank you!

**Comment by DanProudfoot** [comment]
Ok cool - although looking into things more thoroughly, this could all potentially be rewritten using IntersectionObserver? I guess that can be PR v2
